language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
